site_name: Open-Source-Advisor
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_object_full_path: false

nav:
  - Home: index.md
  - API docs: reference.md

repo_url: https://github.com/ITMO-NSS-team/Open-Source-Advisor

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ITMO-NSS-team/Open-Source-Advisor

markdown_extensions:
  - attr_list
  - md_in_html

pages:
  - ['README.md', 'Home']