[tool.poetry]
name = "Open Source Advisor"
version = "0.1.0"
description = "Tool that just makes your open source project better!"
authors = ["ITMO-NSS-team https://github.com/ITMO-NSS-team/"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "3.11.11"
gitdb = "4.0.11"
gitpython = "3.1.43"
PyYAML = "6.0.2"
pydantic-extra-types = "2.9.0"
pydantic = "2.10.5"
requests = "2.32.3"
structlog = "24.4.0"
tiktoken = "0.8.0"
tomli = "2.2.1"
pytest-mock = "3.14.0"
python-dotenv = "1.0.1"
rich = "13.9.4"
readmeai = {git = "https://github.com/fl1pcoin/readmeai.git", rev = "d9bea40bfc188fa8f020a10f6caa739ccb20c016"}

[tool.poetry.group.dev.dependencies]
pytest = "8.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"