# LLM prompts for generating the about section of repositories.

[prompts]

description = """
INPUT DATA:
1. README content: {readme_content}

TASK:
Create a technical, concise GitHub repository description (120 chars) from README content.
Return only the final description text with no commentary.

RULES:
- Third person technical voice.
Focus on:
- Core functionality/automation provided.
- Key technical differentiation.
- Problem domain/specialization.
- Primary architectural pattern.
Avoid:
- Marketing language ('easy', 'powerful')
- Generic verbs('helps with', 'manages')
- Repository type mentions unless novel
Example outputs:
1. 'Dynamic DNS updater with Docker support and Let's Encrypt integration'
2. 'Distributed graph processing engine using actor model parallelism'
"""

topics = """
INPUT DATA:
1. README content: {readme_content}
2. Existing topics: {topics}

TASK:
Analyze the README content and already existing topics to generate up to {amount} specific, technical GitHub topics focusing on:
1. Specialized libraries/packages used (beyond base framework)
2. Core algorithms/technical approaches
3. Specific problem sub-domains
4. Implementation patterns/architectural styles
5. Key technical differentiators
Return only topics as a comma-separated list without explanations.

RULES:
Avoid generic terms like programming languages or frameworks unless they are novel implementations.
Do not change the existing topics.
Format: lowercase, hyphens, technical terms only, use 50 characters per topic or less. 
Example output: computer-vision, graph-algorithms, genetic-algorithm, distributed-systems, gpu-acceleration
"""

analyze_urls = """
INPUT DATA:
1. Repository URL: {project_url}
2. URLs: {urls}

TASK:
Analyze input URLs and return a comma-separated list of valid homepages/documentation sources ranked by relevance excluding any github url. 
Return empty string if none qualify with no commentary or explanations.

RULES:
1. Include:
- OFFICIAL WEBSITE: Root domain (project.com, www.project.org)
- PRIMARY DOCS: Documentation root (docs.project.io) - no subpaths
- GITHUB PAGES: *.github.io (with/without path)
- EXPLICIT HOMEPAGE: External sites clearly designated as main homepage

2. Exclude:
- ALL repository links (github/gitlab/bitbucket URLs - including Project URL itself)
- Repository subpages (/issues, /blob/, /tree/, /raw/)
- CI/CD badges (/badge/, .svg, /actions/)
- Package registries (pypi.org, npmjs.com)
- Social media (twitter.com, linkedin.com)
- Non-root paths (any URL with /subdirectory/)
"""
