name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installing dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: PYTHONPATH=$PWD pytest tests/

  deploy_docs:
    name: Deploy MkDocs
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installing MkDocs dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python]

      - name: Docs deploy
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ITMO-NSS-team/Open-Source-Advisor.git
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
