# Markdown Configuration
[md]

# -- Overview Section ----------------------------------------------------------

overview = """
{0}
"""

# -- Repository Contents Section ------------------------------------------------------------

content = """
{0}
"""

# -- Used Algorithms Section ------------------------------------------------------------

algorithms = """
{0}
"""
